### ISSUE TITLE
Mac OS X backend doesn't work?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/matplotlib-feedstock#94] opened 2016-12-30 22:17 UTC
Seeing this error with `conda-forge`'s `matplotlib`. The error cropped up in the past couple weeks. Appears to show up with build number 4 and not build number 3 of `matplotlib` version `1.5.3`. Not sure if therein lies the cause or if it is a red herring.

```python
    import matplotlib.pyplot as plt
  File "/Users/travis/miniconda3/conda-bld/recipe_1483084010906/_t_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/Users/travis/miniconda3/conda-bld/recipe_1483084010906/_t_env/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/Users/travis/miniconda3/conda-bld/recipe_1483084010906/_t_env/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>
    from matplotlib.backends import _macosx
RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

ref: https://travis-ci.org/conda-forge/openturns-feedstock/jobs/187640795#L5987
ref: https://travis-ci.org/conda-forge/openturns-feedstock/builds/183403638

cc @jschueller @jjhelmus

**Comment by jakirkham** [comment] 2016-12-30 22:19
Maybe related ( https://github.com/conda-forge/matplotlib-feedstock/pull/92 )?

**Comment by dopplershift** [comment] 2016-12-30 23:58
Duplicate of #91 .

**Closed by dopplershift** 2016-12-30 23:58 UTC

**Comment by jakirkham** [comment] 2016-12-31 02:31
Thanks @dopplershift . Does appear to be the case.
