### ISSUE TITLE
Wrong icu version in release candidate on Ubuntu 14.04

### ISSUE THREAD

**Issue by lukepfister** [conda-forge/matplotlib-feedstock#30] opened 2016-06-01 18:09 UTC
I installed the matplotlib release candidate on from conda forge using 
`conda install -c conda-forge/label/rc -c conda-forge matplotlib`.   Trying to use the Qt4Agg backend gives the error:
``` python
ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```

I've fixed this by bumping the icu version via `conda install -c conda-forge icu=56`.

I'm running Ubuntu 14.04.

**Comment by pelson** [comment] 2016-06-01 18:15
Thanks @lukepfister. Looks like we have some packages which depend on ICU but which don't specify which version:

```
conda execute conda-forge.github.io/scripts/list_deps.py conda-forge --dependencies icu --platform osx-64
Fetching package metadata: ..
boost 1.60.0 py27_0 osx-64         : icu
boost 1.60.0 py27_1 osx-64         : icu
boost 1.60.0 py27_2 osx-64         : icu
boost 1.60.0 py27_3 osx-64         : icu 56.*
boost 1.60.0 py34_0 osx-64         : icu
boost 1.60.0 py34_1 osx-64         : icu
boost 1.60.0 py34_2 osx-64         : icu
boost 1.60.0 py34_3 osx-64         : icu 56.*
boost 1.60.0 py35_0 osx-64         : icu
boost 1.60.0 py35_1 osx-64         : icu
boost 1.60.0 py35_2 osx-64         : icu
boost 1.60.0 py35_3 osx-64         : icu 56.*
boost 1.61.0 py27_0 osx-64         : icu 56.*
boost 1.61.0 py34_0 osx-64         : icu 56.*
boost 1.61.0 py35_0 osx-64         : icu 56.*
cairo 1.12.18 1 osx-64             : icu 56.*
libxml2 2.9.3 6 osx-64             : icu
```

Ping @jakirkham. I propose we remove those that don't pin as per https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies. Agree?

**Comment by pelson** [comment] 2016-06-01 18:16
@lukepfister - are you able to create an environment which reproduces the problem and `conda list` it so that we can see exactly which package it was that caused the problem for you?

**Comment by jakirkham** [comment] 2016-06-01 18:50
> Ping @jakirkham. I propose we remove those that don't pin as per https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies. Agree?

SGTM.

**Comment by jakirkham** [comment] 2016-06-01 19:01
Done.

**Comment by lukepfister** [comment] 2016-06-01 23:13
``` bash
# packages in environment at /home/luke/software/python/miniconda/envs/test_env:
#
backports                 1.0                      py35_0    defaults
backports.shutil-get-terminal-size 1.0.0                     <pip>
cycler                    0.10.0                   py35_0    defaults
decorator                 4.0.9                    py35_0    defaults
fontconfig                2.11.1                        2    conda-forge
freetype                  2.6.3                         0    conda-forge
get_terminal_size         1.0.0                    py35_0    defaults
ipython                   4.2.0                    py35_0    defaults
ipython-genutils          0.1.0                     <pip>
ipython_genutils          0.1.0                    py35_0    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          1    conda-forge
libpng                    1.6.17                        0    defaults
libxml2                   2.9.2                         0    defaults
matplotlib                2.0.0b1             np111py35_2    conda-forge
mkl                       11.3.3                        0    defaults
ncurses                   5.9                           7    conda-forge
nomkl                     1.0                           0    defaults
numpy                     1.11.0                   py35_1    defaults
openblas                  0.2.14                        4    defaults
openssl                   1.0.2h                        1    defaults
path.py                   8.2.1                    py35_0    defaults
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.5                      py35_0    defaults
pip                       8.1.1                    py35_1    defaults
ptyprocess                0.5                      py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      4.11.4                   py35_2    defaults
python                    3.5.1                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
pytz                      2016.4                   py35_0    defaults
qt                        4.8.7                         2    defaults
readline                  6.2                           2    defaults
setuptools                21.2.1                   py35_0    defaults
simplegeneric             0.8.1                    py35_0    defaults
sip                       4.16.9                   py35_0    defaults
six                       1.10.0                   py35_0    defaults
sqlite                    3.9.2                         0    defaults
tk                        8.5.18                        0    defaults
traitlets                 4.2.1                    py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
xz                        5.0.5                         1    defaults
zlib                      1.2.8                         3    defaults
```

Of note:  this happens when upgrading from matplotlib 1.5 on the default channel to the 2.0 rc on conda-forge.   Making a clean environment and directly installing the rc from conda-forge worked fine.  Making a clean environment, installing matplotlib from default, then upgrading to the rc reproduces the error.

**Comment by pelson** [comment] 2016-06-02 07:39
I notice your environment doesn't contain an ICU at all. Are you able to track down which file has the ICU dependency so that we can add it to the appropriate package? I'd like to isolate exactly *what* is causing the `ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory` error.

**Comment by lukepfister** [comment] 2016-06-02 21:37
Looks like it is pyqt.  I don't get this error if I'm using, say, the `TkAgg` backend.

``` python 
In [1]: pylab
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-a5df18eabd26> in <module>()
----> 1 get_ipython().magic('pylab ')

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py in magic(self, arg_s)
   2161         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2162         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2163         return self.run_line_magic(magic_name, magic_arg_s)
   2164 
   2165     #-------------------------------------------------------------------------

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2082                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2083             with self.builtin_trap:
-> 2084                 result = fn(*args,**kwargs)
   2085             return result
   2086 

<decorator-gen-107> in pylab(self, line)

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/magics/pylab.py in pylab(self, line)
    154             import_all = not args.no_import_all
    155 
--> 156         gui, backend, clobbered = self.shell.enable_pylab(args.gui, import_all=import_all)
    157         self._show_matplotlib_backend(args.gui, backend)
    158         print ("Populating the interactive namespace from numpy and matplotlib")

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py in enable_pylab(self, gui, import_all, welcome_message)
   2988         from IPython.core.pylabtools import import_pylab
   2989 
-> 2990         gui, backend = self.enable_matplotlib(gui)
   2991 
   2992         # We want to prevent the loading of pylab to pollute the user's

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py in enable_matplotlib(self, gui)
   2949                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   2950 
-> 2951         pt.activate_matplotlib(backend)
   2952         pt.configure_inline_support(self, backend)
   2953 

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/IPython/core/pylabtools.py in activate_matplotlib(backend)
    293     matplotlib.rcParams['backend'] = backend
    294 
--> 295     import matplotlib.pyplot
    296     matplotlib.pyplot.switch_backend(backend)
    297 

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/matplotlib/pyplot.py in <module>()
    112 
    113 from matplotlib.backends import pylab_setup
--> 114 _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
    115 
    116 _IP_REGISTERED = None

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/matplotlib/backends/__init__.py in pylab_setup()
     30     # imports. 0 means only perform absolute imports.
     31     backend_mod = __import__(backend_name,
---> 32                              globals(),locals(),[backend_name],0)
     33 
     34     # Things we pull in from all backends

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py in <module>()
     16 
     17 
---> 18 from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
     19 
     20 from .backend_agg import FigureCanvasAgg

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py in <module>()
     13 
     14 from .backend_agg import FigureCanvasAgg
---> 15 from .backend_qt5 import QtCore
     16 from .backend_qt5 import QtGui
     17 from .backend_qt5 import FigureManagerQT

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py in <module>()
     29     figureoptions = None
     30 
---> 31 from .qt_compat import QtCore, QtGui, QtWidgets, _getSaveFileName, __version__
     32 from matplotlib.backends.qt_editor.formsubplottool import UiSubplotTool
     33 

/home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py in <module>()
    135     # have been changed in the above if block
    136     if QT_API in [QT_API_PYQT, QT_API_PYQTv2]:  # PyQt4 API
--> 137         from PyQt4 import QtCore, QtGui
    138 
    139         try:

ImportError: libicui18n.so.56: cannot open shared object file: No such file or directory
```

**Comment by pelson** [comment] 2016-06-04 06:09
Thanks @lukepfister. 

Could you provide the output from:

```
ldd /home/luke/software/python/miniconda/envs/test_env/lib/python3.5/site-packages/PyQt4/*.so
```

Additionally, it appears Continuum have updated their pyqt (perhaps in response to a similar issue). Could you update to build number 6 to see if this has been resolved (the problem certainly appears to be an Anaconda distribution, rather than a conda-forge one)?

**Comment by lukepfister** [comment] 2016-06-06 14:08
Here you go:  big output, so I put it into a gist.
https://gist.github.com/lukepfister/50ab57ef0c0a21a31963217a3fccb5a5

I re-made my MWE and ran into the same libcui18n problem.  I did a `conda install pyqt`, which then lead to
```
The following packages will be UPDATED:

    fontconfig: 2.11.1-2 --> 2.11.1-4

The following packages will be DOWNGRADED:

    freetype:   2.6.3-0  --> 2.5.5-1 
    libpng:     1.6.21-0 --> 1.6.17-0
```
and the problem was resolved.

Looks like I'm still on build 4 of pyqt.  I'll poke around on it some more later this week.

I'm in way over my head on this one-  but happy to provide any extra information.
and the

**Comment by janschulz** [comment] 2016-06-06 14:18
The "`conda install pyqt` downgrades libpng" is discussed here: https://github.com/conda-forge/conda-forge.github.io/issues/157#issuecomment-223536381

**Comment by ocefpaf** [comment] 2016-06-16 15:04
I believe #29 fixed that. it @lukepfister can you test it and let is know if t works for you?

**Comment by lukepfister** [comment] 2016-06-17 16:05
@ocefpaf libpng is no longer being downgraded, but I'm having the same icu issue.

**Comment by ocefpaf** [comment] 2016-06-17 16:07
Thanks for testing it @lukepfister. Are you still installing the release candidate (`conda-forge/label/rc`)? I haven't checked that yet...

**Comment by lukepfister** [comment] 2016-06-19 13:53
Yes, that was still using the rc.

**Comment by ocefpaf** [comment] 2016-06-28 15:24
@lukepfister I believe I found the culprit and `icu` should be pulled now. I test it in a docker image with success. Can you confirm if that is fixed on your end?

PS: It was some bad build number that were not properly pinned holding the overall version solver to download the proper verision of the package that brings `icu`.

**Comment by pelson** [comment] 2016-06-30 11:48
Closing, as it sounds like this has been resolved. Please re-open if incorrect @lukepfister.

Thanks @ocefpaf!

**Closed by pelson** 2016-06-30 11:48 UTC
