### ISSUE TITLE
Windows: problem with beta3 vs freetype conflict

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda-forge/matplotlib-feedstock#46] opened 2016-07-20 20:18 UTC
When trying to install the 2.0.0b3 beta version, I get the message that there is a conflict with freetype (which would not be available for windows). However, if can it install it manually, and then installing the beta does work:

Making a fresh env and trying to install the beta:

```
C:\Users\vdbosscj>conda create -n test-matplotlib python=2
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda\envs\test-matplotlib:

The following NEW packages will be INSTALLED:

    pip:            8.1.2-py27_0   defaults
    python:         2.7.12-0       defaults
    setuptools:     23.0.0-py27_0  defaults
    vs2008_runtime: 9.00.30729.1-2 defaults
    wheel:          0.29.0-py27_0  defaults

...

(test-matplotlib) C:\Users\vdbosscj>conda install matplotlib=2.0.0b3 -c conda-forge/label/rc
Fetching package metadata ...........
Solving package specifications: .
Error: Dependency missing in current win-64 channels:
  - matplotlib 2.0.0b3* -> freetype 2.6*
```

However, I can install it manually:

```
(test-matplotlib) C:\Users\vdbosscj>conda install freetype=2.6 -c conda-forge
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda\envs\test-matplotlib:

The following NEW packages will be INSTALLED:

    freetype: 2.6.3-vc9_1  conda-forge [vc9]
    libpng:   1.6.23-vc9_0 conda-forge [vc9]
    zlib:     1.2.8-vc9_3  conda-forge [vc9]

Proceed ([y]/n)?

Pruning fetched packages from the cache ...
Fetching packages ...
zlib-1.2.8-vc9 100% |###############################| Time: 0:00:00 261.64 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

```

And now installing the beta works:

```
(test-matplotlib) C:\Users\vdbosscj>conda install matplotlib=2.0.0b3 -c conda-forge/label/rc
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda\envs\test-matplotlib:

The following NEW packages will be INSTALLED:

    cycler:          0.10.0-py27_0       defaults
    functools32:     3.2.3.2-py27_0      defaults
    jpeg:            8d-vc9_0            defaults             [vc9]
    libtiff:         4.0.6-vc9_2         defaults             [vc9]
    matplotlib:      2.0.0b3-np111py27_3 conda-forge/label/rc
    mkl:             11.3.3-1            defaults
    numpy:           1.11.1-py27_0       defaults
    openssl:         1.0.2h-vc9_0        defaults             [vc9]
    pyparsing:       2.1.4-py27_0        defaults
    pyqt:            4.11.4-py27_7       defaults
    python-dateutil: 2.5.3-py27_0        defaults
    pytz:            2016.6.1-py27_0     defaults
    qt:              4.8.7-vc9_9         defaults             [vc9]
    sip:             4.18-py27_0         defaults
    six:             1.10.0-py27_0       defaults

Proceed ([y]/n)?

Pruning fetched packages from the cache ...
Fetching packages ...
libtiff-4.0.6- 100% |###############################| Time: 0:00:00 566.37 kB/s
pytz-2016.6.1- 100% |###############################| Time: 0:00:00 317.75 kB/s
sip-4.18-py27_ 100% |###############################| Time: 0:00:00 399.65 kB/s
six-1.10.0-py2 100% |###############################| Time: 0:00:00 148.73 kB/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   1.79 MB/s
qt-4.8.7-vc9_9 100% |###############################| Time: 0:02:55 300.46 kB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:08 476.92 kB/s
matplotlib-2.0 100% |###############################| Time: 0:00:12 537.14 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
        1 file(s) copied.######################################          |  80%
[      COMPLETE      ]|##################################################| 100%

```

**Comment by ocefpaf** [comment] 2016-07-31 12:29
@jorisvandenbossche this should be fixed in #49

Let me know if that works for you.

**Comment by jorisvandenbossche** [comment] 2016-08-15 18:15
Just tested this, and I still get the same error:

```
C:\Users\vdbosscj>conda create -n test-matplotlib python=2

[...]

C:\Users\vdbosscj>activate test-matplotlib

(test-matplotlib) C:\Users\vdbosscj>conda install matplotlib=2.0.0b3 -c conda-forge/label/rc
Fetching package metadata ...........
Solving package specifications: .
Error: Dependency missing in current win-64 channels:
  - matplotlib 2.0.0b3* -> freetype 2.6.*

You can search for packages on anaconda.org with

    anaconda search -t conda freetype
```

**Comment by ocefpaf** [comment] 2016-08-15 18:29
The package does exist.

```shell
conda search -c defaults --platform win-64 freetype
freetype
                             2.6.3                    vc10_0  conda-forge/win-64 [vc10
                             2.6.3                    vc14_0  conda-forge/win-64 [vc14
                             2.6.3                     vc9_0  conda-forge/win-64 [vc9]
                             2.6.3                    vc10_1  conda-forge/win-64 [vc10
                             2.6.3                    vc14_1  conda-forge/win-64 [vc14
                             2.6.3                     vc9_1  conda-forge/win-64 [vc9]
```

I will try to get a Windows machine to see if I can debug this.

**Comment by jorisvandenbossche** [comment] 2016-08-15 18:42
If there is anything I can try to debug, let me know

**Comment by msarahan** [comment] 2016-08-15 21:10
These conda unsatisfiable warnings are practically always about some dependency further down in the stack.  I do not know a better way to debug other than to work backwards, building and examining one recipe at a time, until you find the root cause.

**Comment by janssen** [comment] 2017-01-11 02:39
I'm seeing the same issue with 2.0.0rc1.

**Comment by ocefpaf** [comment] 2017-03-23 21:38
I am closing this due to inactivity. We already moved to `freetype 2.7` as well.

Let me know if any of you are still facing issues like this though.

**Closed by ocefpaf** 2017-03-23 21:38 UTC

**Comment by jorisvandenbossche** [comment] 2017-03-23 21:59
In any case, the above example commands work for the released version on conda-forge, so that is more important than an old beta :-)
