### ISSUE TITLE
Crash on macOS with default backend

### ISSUE THREAD

**Issue by egpbos** [conda-forge/matplotlib-feedstock#200] opened 2019-02-19 09:38 UTC
When I install matplotlib into a clean environment (using conda-forge as the first and defaults as the second channel in my ~/.condarc):

```sh
conda create -n mpl_crash_conda matplotlib
conda activate mpl_crash_conda
```

And try to plot from the interpreter:

```python
import matplotlib.pyplot as plt
plt.plot([0,1],[2,3])
```

the interpreter crashes, printing the following:

<details>

```sh
2019-02-19 10:27:49.651 python[52009:428477] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7ff001dbce10
2019-02-19 10:27:49.654 python[52009:428477] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7ff001dbce10'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff422b7ded __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff6e383720 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff42335195 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff42259a60 ___forwarding___ + 1486
	4   CoreFoundation                      0x00007fff42259408 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000011951c134 TkpInit + 324
	6   libtk8.6.dylib                      0x00000001194740ce Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x0000000116b41a3f _tkinter_create + 1183
	8   python                              0x00000001068c6086 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x0000000106a061b7 call_function + 247
	10  python                              0x0000000106a03ce7 _PyEval_EvalFrameDefault + 45287
	11  python                              0x00000001069f7932 _PyEval_EvalCodeWithName + 418
	12  python                              0x00000001068c4d57 _PyFunction_FastCallDict + 231
	13  python                              0x00000001069489b1 slot_tp_init + 193
	14  python                              0x0000000106952971 type_call + 241
	15  python                              0x00000001068c5a53 _PyObject_FastCallKeywords + 179
	16  python                              0x0000000106a06254 call_function + 404
	17  python                              0x0000000106a03ddb _PyEval_EvalFrameDefault + 45531
	18  python                              0x00000001068c5848 function_code_fastcall + 120
	19  python                              0x0000000106a0616e call_function + 174
	20  python                              0x0000000106a03ce7 _PyEval_EvalFrameDefault + 45287
	21  python                              0x00000001069f7932 _PyEval_EvalCodeWithName + 418
	22  python                              0x00000001068c4d57 _PyFunction_FastCallDict + 231
	23  python                              0x00000001068c8c72 method_call + 130
	24  python                              0x00000001068c66c2 PyObject_Call + 130
	25  python                              0x0000000106a03f4f _PyEval_EvalFrameDefault + 45903
	26  python                              0x00000001069f7932 _PyEval_EvalCodeWithName + 418
	27  python                              0x00000001068c5f53 _PyFunction_FastCallKeywords + 195
	28  python                              0x0000000106a0616e call_function + 174
	29  python                              0x0000000106a03d22 _PyEval_EvalFrameDefault + 45346
	30  python                              0x00000001068c5848 function_code_fastcall + 120
	31  python                              0x0000000106a0616e call_function + 174
	32  python                              0x0000000106a03d22 _PyEval_EvalFrameDefault + 45346
	33  python                              0x00000001069f7932 _PyEval_EvalCodeWithName + 418
	34  python                              0x00000001068c5f53 _PyFunction_FastCallKeywords + 195
	35  python                              0x0000000106a0616e call_function + 174
	36  python                              0x0000000106a03d22 _PyEval_EvalFrameDefault + 45346
	37  python                              0x00000001069f7932 _PyEval_EvalCodeWithName + 418
	38  python                              0x00000001068c5f53 _PyFunction_FastCallKeywords + 195
	39  python                              0x0000000106a0616e call_function + 174
	40  python                              0x0000000106a03ce7 _PyEval_EvalFrameDefault + 45287
	41  python                              0x00000001069f7932 _PyEval_EvalCodeWithName + 418
	42  python                              0x0000000106a5e7ad PyRun_InteractiveOneObjectEx + 1197
	43  python                              0x0000000106a5b361 PyRun_InteractiveLoopFlags + 321
	44  python                              0x0000000106a5b1b0 PyRun_AnyFileExFlags + 64
	45  python                              0x0000000106a8832e pymain_main + 11102
	46  python                              0x00000001068983ed main + 125
	47  libdyld.dylib                       0x00007fff6f451ed9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
[1]    52009 abort      python
```
</details>

This seems identical to what happened [here](https://github.com/MTG/sms-tools/issues/36#issuecomment-457927535). However, the proposed solution should not be necessary, since Matplotlib is perfectly capable of detecting the correct backend itself, as evidenced by this output in a clean interpreter:

```python
>>> import matplotlib as mpl
>>> mpl.get_backend()
'TkAgg'
```

This seems to be an issue specific to the Conda package. Installing with pip works fine, although there Matplotlib does behave differently: it defaults to the `macosx` backend, and complains when running from a non-framework interpreter. Does the Conda version (or rather the pypi version) have some patch that makes it behave differently (if so, perhaps it's broken)?

Note that both the conda-forge and the defaults Conda packages have this problem. Creating the environment with `-c defaults` to force its precedence over my ~/.condarc gives the same error.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/pbos/sw/miniconda3/envs/mpl_crash_conda:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
freetype                  2.9.1             h597ad8a_1005    conda-forge
intel-openmp              2019.1                      144
kiwisolver                1.0.1           py37h04f5b5a_1002    conda-forge
libcxx                    7.0.0                h2d50403_2    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgfortran               3.0.1                h93005f0_2
libpng                    1.6.36            ha441bb4_1000    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
matplotlib                3.0.2                 py37_1002    conda-forge
matplotlib-base           3.0.2           py37hf043ca5_1002    conda-forge
mkl                       2019.1                      144
mkl_fft                   1.0.10           py37h1de35cc_1    conda-forge
mkl_random                1.0.2            py37h1702cab_2    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.15.4           py37hacdab7b_0
numpy-base                1.15.4           py37h6575580_0
openssl                   1.0.2p            h1de35cc_1002    conda-forge
pip                       19.0.2                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
python                    3.7.1             h145921a_1000    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
sqlite                    3.26.0            h1765d9f_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
tornado                   5.1.1           py37h1de35cc_1000    conda-forge
wheel                     0.33.0                   py37_0    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : mpl_crash_conda
    active env location : /Users/pbos/sw/miniconda3/envs/mpl_crash_conda
            shell level : 3
       user config file : /Users/pbos/.condarc
 populated config files : /Users/pbos/.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /Users/pbos/sw/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/pbos/sw/miniconda3/pkgs
                          /Users/pbos/.conda/pkgs
       envs directories : /Users/pbos/sw/miniconda3/envs
                          /Users/pbos/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.4 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

**Comment by egpbos** [comment] 2019-02-19 09:41
Further note: doing `import matplotlib as mpl; mpl.use('TkAgg')` before any plotting does work. However, as explained above, this is something that `mpl` should be able to do automatically, using `mpl.get_backend()`, which correctly identifies `TkAgg` as the one to use.

**Comment by dopplershift** [comment] 2019-02-19 20:59
I can reproduce. Interestingly, if pyqt is installed, the crash goes away as well.

**Comment by jjhelmus** [comment] 2019-02-20 00:10
I believe this is a know issue with matplotlib and has been fixed in master, see matplotlib/matplotlib#13096

**Comment by egpbos** [comment] 2019-02-20 10:52
Yep, that seems to be it @jjhelmus. So we'll have to wait for 3.0.3?

**Comment by egpbos** [comment] 2019-02-20 10:55
Also: is there any chance we can speed up that release? Where/how is this decided?

**Comment by dopplershift** [comment] 2019-02-20 20:05
@egpbos It looks like the linked issues contains a diff that fixes the issue. Would you be interesting in submitting a PR that adds that diff as a patch to the recipe? You can model it off the existing patch we already have.

**Comment by egpbos** [comment] 2019-02-21 13:44
v3.0.3 is planned to be released tonight, so it's probably easier to wait for that and update the package.

**Comment by egpbos** [comment] 2019-02-27 07:19
Sadly, 3.0.3 still exhibits the exact same issue.

**Comment by egpbos** [comment] 2019-02-27 07:37
Regarding my suspicion that Conda may be using a patch that the pip version isn't: it turns out it's actually the other way around :) See this comment: https://github.com/ContinuumIO/anaconda-issues/issues/10219#issuecomment-433715899

I'm not sure whether this would be an ideal fix, but it's perhaps something to consider for this package as well, though the discussion in that thread (mainly this comment: https://github.com/ContinuumIO/anaconda-issues/issues/10219#issuecomment-457220949) leads me to suspect that neither the Conda nor the pip package should change any defaults.

**Comment by danlipsa** [comment] 2019-03-01 18:13
I also see a crash with python 3.7:

```
(test) [~/projects/cdat/vcs (master $%=)]$ conda install python=3.7 matplotlib

Solving environment: done





==> WARNING: A newer version of conda exists. <==

  current version: 4.5.12

  latest version: 4.6.7



Please update conda by running



    $ conda update -n base conda







## Package Plan ##



  environment location: /Users/danlipsa/anaconda3/envs/test



  added / updated specs: 

    - matplotlib

    - python=3.7





The following NEW packages will be INSTALLED:



    blas:            1.0-mkl                            

    bzip2:           1.0.6-h1de35cc_1002     conda-forge

    ca-certificates: 2018.11.29-ha4d7672_0   conda-forge

    certifi:         2018.11.29-py37_1000    conda-forge

    cycler:          0.10.0-py_1             conda-forge

    freetype:        2.9.1-h597ad8a_1005     conda-forge

    intel-openmp:    2019.1-144                         

    kiwisolver:      1.0.1-py37h04f5b5a_1002 conda-forge

    libcxx:          7.0.0-h2d50403_2        conda-forge

    libffi:          3.2.1-h0a44026_1005     conda-forge

    libgfortran:     3.0.1-0                 conda-forge

    libpng:          1.6.36-ha441bb4_1000    conda-forge

    llvm-meta:       7.0.0-0                 conda-forge

    matplotlib:      3.0.3-py37_0            conda-forge

    matplotlib-base: 3.0.3-py37hf043ca5_0    conda-forge

    mkl:             2019.1-144                         

    mkl_fft:         1.0.10-py37h1de35cc_1   conda-forge

    mkl_random:      1.0.2-py37h1702cab_2    conda-forge

    ncurses:         6.1-h0a44026_1002       conda-forge

    numpy:           1.15.4-py37hacdab7b_0              

    numpy-base:      1.15.4-py37h6575580_0              

    openssl:         1.1.1a-h1de35cc_1000    conda-forge

    pip:             19.0.3-py37_0           conda-forge

    pyparsing:       2.3.1-py_0              conda-forge

    python:          3.7.1-hbdd33cc_1002     conda-forge

    python-dateutil: 2.8.0-py_0              conda-forge

    readline:        7.0-hcfe32e1_1001       conda-forge

    setuptools:      40.8.0-py37_0           conda-forge

    six:             1.12.0-py37_1000        conda-forge

    sqlite:          3.26.0-h1765d9f_1000    conda-forge

    tk:              8.6.9-ha441bb4_1000     conda-forge

    tornado:         5.1.1-py37h1de35cc_1000 conda-forge

    wheel:           0.33.1-py37_0           conda-forge

    xz:              5.2.4-h1de35cc_1001     conda-forge

    zlib:            1.2.11-h1de35cc_1004    conda-forge



Proceed ([y]/n)? y



Preparing transaction: done

Verifying transaction: done

Executing transaction: done

(test) [~/projects/cdat/vcs (master $%=)]$ python m.py 

2019-02-26 18:37:56.503 python[3906:346767] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7f89d1c6f9d0

2019-02-26 18:37:56.505 python[3906:346767] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7f89d1c6f9d0'

*** First throw call stack:

(

	0   CoreFoundation                      0x00007fff36500ded __exceptionPreprocess + 256

	1   libobjc.A.dylib                     0x00007fff625c8720 objc_exception_throw + 48

	2   CoreFoundation                      0x00007fff3657e195 -[NSObject(NSObject) __retain_OA] + 0

	3   CoreFoundation                      0x00007fff364a2a60 ___forwarding___ + 1486

	4   CoreFoundation                      0x00007fff364a2408 _CF_forwarding_prep_0 + 120

	5   libtk8.6.dylib                      0x0000000116e37134 TkpInit + 324

	6   libtk8.6.dylib                      0x0000000116d8f0ce Initialize + 2622

	7   _tkinter.cpython-37m-darwin.so      0x0000000116bb8a3f _tkinter_create + 1183

	8   python                              0x0000000102f1b0a6 _PyMethodDef_RawFastCallKeywords + 230

	9   python                              0x000000010305b0d7 call_function + 247

	10  python                              0x0000000103058c0d _PyEval_EvalFrameDefault + 45325

	11  python                              0x000000010304c832 _PyEval_EvalCodeWithName + 418

	12  python                              0x0000000102f19d77 _PyFunction_FastCallDict + 231

	13  python                              0x0000000102f9d851 slot_tp_init + 193

	14  python                              0x0000000102fa7811 type_call + 241

	15  python                              0x0000000102f1aa73 _PyObject_FastCallKeywords + 179

	16  python                              0x000000010305b174 call_function + 404

	17  python                              0x0000000103058d01 _PyEval_EvalFrameDefault + 45569

	18  python                              0x0000000102f1a868 function_code_fastcall + 120

	19  python                              0x000000010305b08e call_function + 174

	20  python                              0x0000000103058c0d _PyEval_EvalFrameDefault + 45325

	21  python                              0x000000010304c832 _PyEval_EvalCodeWithName + 418

	22  python                              0x0000000102f19d77 _PyFunction_FastCallDict + 231

	23  python                              0x0000000102f1dc82 method_call + 130

	24  python                              0x0000000102f1b6e2 PyObject_Call + 130

	25  python                              0x0000000103058e75 _PyEval_EvalFrameDefault + 45941

	26  python                              0x000000010304c832 _PyEval_EvalCodeWithName + 418

	27  python                              0x0000000102f19d77 _PyFunction_FastCallDict + 231

	28  python                              0x0000000103058e75 _PyEval_EvalFrameDefault + 45941

	29  python                              0x000000010304c832 _PyEval_EvalCodeWithName + 418

	30  python                              0x0000000102f1af73 _PyFunction_FastCallKeywords + 195

	31  python                              0x000000010305b08e call_function + 174

	32  python                              0x0000000103058c0d _PyEval_EvalFrameDefault + 45325

	33  python                              0x000000010304c832 _PyEval_EvalCodeWithName + 418

	34  python                              0x00000001030b10e0 PyRun_FileExFlags + 256

	35  python                              0x00000001030b0557 PyRun_SimpleFileExFlags + 391

	36  python                              0x00000001030dccc3 pymain_main + 9651

	37  python                              0x0000000102eed3dd main + 125

	38  libdyld.dylib                       0x00007fff63696ed9 start + 1

	39  ???                                 0x0000000000000002 0x0 + 2

)

libc++abi.dylib: terminating with uncaught exception of type NSException

Abort trap: 6

(test) [~/projects/cdat/vcs (master $%=)]$ 

```

**Comment by jjhelmus** [comment] 2019-03-02 19:40
The root cause of the issue is that in 3.0.2 and 3.0.3 (and perhaps other 3.0.x releases) `matplotlib.get_backend()` or `import matplotlib.pyplot as plt` triggers the logic which tried to find a preferred backend if no backend is specified by another means.  This loads `matplotlib.backends._macosx` on macOS, and on non-framework builds like the conda provided Python this import fails. After this the `TkAgg` backend is loaded. Because the macosx backend has also been partially loaded the TkAgg backend does not function properly which causes the crash. See matplotlib/matplotlib#13096 for more discussion on this topic.

One option would be to set `tkagg` as the default backend in the `matplotlibrc` file which ships in the matplotlib-base conda package.  This would prevent the `macosx` backend from being loaded and prevent this crash.  The matplotlib wheel does something similar except it sets `macosx` as the default backend.  The `macosx` backend should not be set as the default in the conda package as the conda provided Python is a non-framework build and does not directly support this backend, see conda-forge/python-feedstock#23.

It should also be noted that if the `python.app` package is installed and pythonw is used to run scripts the`macosx` backend can be used without issues.

**Comment by egpbos** [comment] 2019-03-04 14:37
Thanks for this excellent analysis @jjhelmus!

**Comment by jklymak** [comment] 2019-03-08 16:56
Sorry this has been a nuisance.  We think its fixed per matplotlib/matplotlib#13096.  On matplotlib master, with no `~/.matplotlib/matplotlibrc`

```
conda create -n mpl_crash_conda matplotlib
pip install -e .
```
and then from the interpreter:
```
>>> import matplotlib.pyplot as plt
>>> plt.plot([0,1],[2,3])
[<matplotlib.lines.Line2D object at 0x1128d6c50>]
>>> plt.show()
```

I get a macosx GUI window opening w/ the figure.

```
>>> import matplotlib
>>> print(matplotlib.get_backend())
MacOSX
```

If folks with install problems could try that out it would be very helpful. OTOH I'm personally somewhat lost as to what exactly conda does, so if there is other testing we should do before cutting 3.1 that suggestions would be gratefully received.  The active devs with Macs like myself tend not to be experts on the build machinery, and given the compelxities of different python environments its not always easy to ferret out what the conda version will look like to end users.

FWIW, most of the devs seem to use Qt5agg as their backend.  Thats not meant as an excuse, but if all else fails it is a reasonable work around to set that in your `matplotlibrc` as a default.  

ping @anntzer @tacaswell for more expert commentary....

I'll note that I cannot reproduce the Tk/_macosx collision reported above with 3.0.3 installed as reported above.  However instead of triggering the `MacOSX` backend, I get `TkAgg`.   This is with python 3.7.

**Comment by jjhelmus** [comment] 2019-03-08 18:09
@jklymak Are you activating the conda environment before you run `pip install -e .`?  If not then you installing using whatever pip and python are currently on PATH not the conda provided versions.  

The key difference for conda Python on Mac vs the Python.org Python is that `python` is not a framework build and therefore the `MacOSX` backend does not work due to [the verify_framework check](https://github.com/matplotlib/matplotlib/blob/v3.0.3/src/_macosx.m#L2578-L2608).  The `pythonw` executable from the `python.app` conda package is needed to enable Framework support.

One option would be for the conda package to set the default backend to `Qt5Agg` on macOS.  Another would be to port the [2.2.x patch](https://github.com/conda-forge/matplotlib-feedstock/blob/v2.2.x/recipe/osx-frame.patch) which removed the `verify_framework` check and enable the use of the `MacOSX` backend on conda's non-framework build.

**Comment by jklymak** [comment] 2019-03-08 18:25
Sorry, yes, I am activating the environement.  Edited the above...

Patches like that 2.2.x patch on the conda feed side can be confusing because the bug reports come to matplotlib, and then we can't reproduce.  Removing that check indeed allows the mac gui to spin up, but it has weird focus issues (I think if you open the save dialog, for instance, you can't actually type in the dialog box) and leads to bug reports so that it was decided to put the check in. 

However, from what we can tell https://github.com/matplotlib/matplotlib/pull/12633 is meant to remove the framework restriction by changing the `[NSApp setActivationPolicy:NSApplicationActivationPolicyRegular]` .   This is milestoned for 3.1.  Further testing, though, would be *very* welcome~

**Comment by anntzer** [comment] 2019-03-10 19:44
Some googling shows that one should in theory know whether a python build is a framework build just by querying sysconfig (https://stackoverflow.com/a/15752676/378080, from a cpython core dev), but IIRC (well, I looked that up before implementing verify_framework) conda's python.app is built in such a way that this doesn't actually work.  If the conda devs could provide a better way to check the frameworkness of python, I'm sure we could use that in matplotlib.

**Comment by ocefpaf** [comment] 2019-05-26 15:14
Looks like this was fixed and we have a new version since this issue was opened. If the problem persists please reopen.

**Closed by ocefpaf** 2019-05-26 15:14 UTC

**Comment by egpbos** [comment] 2019-06-12 10:45
Confirmed! The procedure in the OP now works. Also, `mpl.get_backend()` now gives `'MacOSX'` in a clean interpreter.
